go-chassis/go-chassis

.travis.yml
README.md
scripts/travis/deadCodeChecker.sh
scripts/travis/formatChecker.sh

https://github.com/ServiceComb/go-chassis/issues/3
Preview :

Add Travis Configuration

---

auth/auth_test.go
bootstrap/bootstrap_test.go
chassis.go
config-center/config_center.go
config-center/config_center_test.go
core/archaius/archaius.go
core/archaius/archaius_test.go
core/archaius/fault_injection_config.go
core/config/config.go
core/fault/fault_injection.go
core/handler/bizkeeper_handler_test.go
core/handler/loadbalance_handler_test.go
core/handler/qps_provider_flow_control_handler.go
core/handler/transport_handler_test.go
core/qpslimiter/qps_limiter_test.go
core/route/router_test.go
core/tls/tls_test.go
eventlistener/circuit_breaker_event_listener_test.go
eventlistener/lb_test.go
eventlistener/qps_event_listener_test.go
metrics/metric_test.go

1. handle fault injection percentage mutation 
2. fix qpslimiter global configuration inoperative problem

handle fault injection percentage mutation and fix qpslimiter global config problem

---

.travis.yml
auth/auth_test.go
client/highway/highway_test.go
core/config/schema/loader_test.go
core/handler/tracing_handler_test.go
core/route/router_test.go
core/tls/tls_test.go
core/transport/transport_manager_test.go
metrics/metric_test.go
scripts/travis/goVetChecker.sh
scripts/travis/unit_test.sh
util/fileutil/fileutil.go

Signed-off-by: asifdxtreme <mohammad.asif.siddiqui1@huawei.com>

Configure Unit-Test to run with CI

---

.gitignore
core/transport/transport_manager_test.go
scripts/travis/unit_test.sh
vendor/manifest

Download all file of servicecomb project;
Add some ignored files;
Edit failed test case in transport/transport_manager_test.go.

Download all file of servicecomb project;

---

.travis.yml
core/handler/transport_handler.go
scripts/travis/goCycloChecker.sh

Added GoCyclo Travis Configuration

Added travis configuration

---

core/handler/tracing_handler.go
core/handler/tracing_handler_test.go
core/tracing/collector.go
core/tracing/collector_test.go
core/tracing/namedpipe_collector_test.go
vendor/manifest

this PR fixed #30 
update the imported  `zipkincore`  to latest and adjust vendor manifest.json

fix go get errors

---

third_party/forked/benbjohnson/clock/README.md
third_party/forked/kubernetes/README.md
third_party/forked/kubernetes/code-of-conduct.md
third_party/forked/uber-go/ratelimit/README.md

Signed-off-by: WangQilin <qilin.wang@huawei.com>

add missed third_party README.md

---

vendor/manifest

added uber pkg in manifest

---

client/highway/worker.go

https://github.com/ServiceComb/go-chassis/issues/20 highway client hang

#20 highway client hang

---

server/restful/context.go

Open API to expose native rw

---

core/loadbalance/latency_strategy.go

Bug fix for latency aware loadbalance strategy
https://github.com/ServiceComb/go-chassis/issues/90

bug fix for latency aware loadbalance strategy

---

LICENSE
NOTICE
util/iputil/ip.go

rewrite GetlocalIP

---

core/archaius/cb_config_test.go
core/handler/tracing_handler.go
server/restful/restful_server.go

Once this PR merge will change the cyclo value to 16 in
https://github.com/ServiceComb/go-chassis/blob/master/scripts/travis/goCycloChecker.sh#L1

Modified code to reach cyclo metric complexity to 16

---

client/rest/restful.go
client/rest/restful_test.go

Signed-off-by: WangQilin <qilin.wang@huawei.com>

fix missing headers in Request Copy()

---

client/rest/rest_client.go
core/handler/transport_handler.go
core/loadbalancer/latency_strategy.go
core/loadbalancer/latency_strategy_test.go
core/loadbalancer/load_balancer.go
core/loadbalancer/struct.go

…s choose the lowest latency instance

rewrote weighted response strategy to optimize perf and don not alway choose lowest latency instance

---

core/common/common.go
core/config/config.go
core/config/config_test.go
examples/discovery/server/conf/chassis.yaml

Added changes to support SERVICE_NAME and VERSION as a environment variable to support in k8s.

---

.travis.yml
vendor/manifest

Signed-off-by: WangQilin <qilin.wang@huawei.com>

remove unused packages in vendor/manifest

---

core/loadbalancer/latency_strategy.go
core/loadbalancer/randam.go

https://github.com/ServiceComb/go-chassis/issues/161

Fix Concurrent map read write for WeightedResponse Strategy

---

chassis.go
client/rest/restful.go
examples/discovery/client/main.go
examples/schemas/restful_hello.go

SetCookie panic problem

---

chassis.go
core/config/config.go
core/config/model/router.go
core/handler/loadbalance_handler.go
core/registry/bootstrap.go
core/registry/util.go
core/registry/util_test.go
core/router/cse/darklaunch.go
core/router/cse/router.go
core/router/cse/router_manager.go
core/router/cse/router_manager_test.go
core/router/cse/translate.go
core/router/router.go
core/router/router_config.go
core/router/router_test.go
eventlistener/router_event_listener.go
eventlistener/router_event_listener_test.go
examples/discovery/client/conf/router.yaml
util/fileutil/fileutil.go
util/fileutil/fileutil_test.go

unify config into one package
to adapt to diffrent Infra like Pilot and some API, add router interface to fetch Route rule
fix bug advertise address doesn't support 127.0.0.1

router rule can comes from an infra

---

core/common/common.go
core/config/sr_config.go
core/handler/handler_chain.go
core/metadata/framework.go
core/registry/bootstrap.go
examples/communication/README.md
examples/communication/client/main.go
examples/communication/server/main.go
examples/discovery/client/main.go
examples/discovery/server/main.go
examples/fileupload/client/main.go
examples/fileupload/server/main.go
examples/rest/client/main.go
examples/rest/server/main.go
examples/rpc/client/main.go
examples/rpc/server/main.go
metrics/metric.go
server/restful/restful_server.go

by default enable app invocation

---

client/highway/highway_msgobj.go
server/highway/highway_conn.go

don't print EOF error

---

docs/user-guides.rst
docs/user-guides/protocols.md

#213 add protocol doc

---

client/highway/highway_client.go
client/rest/rest_client.go
client/rest/rest_client_test.go
core/client/client.go
core/core_test.go
core/handler/loadbalance_handler.go
core/handler/transport_handler.go
core/invocation/invocation.go
core/loadbalancer/load_balancer.go
core/options.go
docs/user-guides/filter.md
healthz/client/test.go
server/highway/highway_server_test.go
server/restful/restful_server.go

change client interface to only accept invocation, the developer care about how to transfer it in to protocol request

change WithFilter to accept function name instead of function

---

core/config/config.go

修改 parseRouterConfig 的注释

---

core/registry/healthz.go
core/registry/healthz_test.go
core/registry/servicecenter/cache.go
core/registry/servicecenter/sc_convertor.go
core/registry/servicecenter/servicecenter.go

Fix the HC conflict between chassis and mesher #298

---

chassis.go
chassis_test.go
control/archaius/panel.go
control/istio/panel.go
control/panel.go
control/panel_test.go
core/config/config.go
core/config/model/chassis.go
core/config/model/control.go
core/handler/bizkeeper_consumer_handle.go
core/handler/bizkeeper_handler_test.go

new feature: control panel

---

core/registry/servicecenter/cache.go

https://github.com/go-chassis/go-chassis/issues/295

Fix IndexSchema MemoryLeak

---

core/registry/cache.go
core/registry/cache_test.go
core/registry/servicecenter/cache.go
core/registry/servicecenter/servicecenter.go

alter provider trust local cache，not trust sc provider

alter Provider trust local cache

---

core/archaius/archaius_test.go
go.mod

Issue : https://github.com/go-chassis/go-archaius/issues/30

Added Test scenario to check the content of file which is added during runtime

---

benchmark/client/conf/chassis.yaml
benchmark/server/conf/chassis.yaml
chassis.go
client/rest/rest_client.go
core/client/client_manager.go
core/client/client_manager_test.go
core/config/config.go
core/config/model/chassis.go
core/handler/handler.go
core/server/server_test.go
docs/user-guides.rst
docs/user-guides/handler-chain.md
docs/user-guides/protocols.md
docs/user-guides/transport.md
examples/discovery/client/conf/chassis.yaml
examples/discovery/client/conf/circuit_breaker.yaml
examples/monitoring/client/conf/monitoring.yaml
tracing/zipkin/zipkin.go

remove default http error status
write new doc about how to define transport failure
fix tracing init collector option error

remove circuit breaker from default handler chain

---

docs/getstarted/pilot-discovery.md
docs/istio-guides.rst
docs/istio/discovery.rst
docs/istio/getstarted.md
docs/istio/router.md
docs/user-guides/service-discovery.md

Add the Istio pilot service discovery docs in getting started section.

Add the docs on how to get started with Istio pilot

---

core/config/model/chassis.go
core/registry/bootstrap.go
core/registry/servicecenter/sc_convertor.go
core/registry/struct.go
docs/user-guides/microservice.md

Post ServicePaths while Registering to SC ( https://github.com/go-chassis/go-chassis/issues/432 )

Post ServicePaths while Registering to SC

---

control/archaius/panel.go
control/panel.go
control/strcut.go

Control panel changes for Egress

Control panel changes for Egress

---

benchmark/README.md
benchmark/conf/circuit_breaker.yaml
benchmark/util/benchmark.go
benchmark/util/http.go
client/grpc/grpc.go
client/rest/rest_client.go
control/archaius/panel_test.go
control/archaius/transfer.go
control/archaius/transfer_test.go
core/client/client_manager.go
core/config/cb_config.go
core/handler/bizkeeper_consumer_handle.go
go.mod
third_party/forked/afex/hystrix-go/hystrix/hystrix.go
third_party/forked/afex/hystrix-go/hystrix/settings.go
third_party/forked/afex/hystrix-go/hystrix/settings_test.go

#421 after circuit open because of timeout， that case will cause mem leak

fix timeout mem leak in circuit breaker

---

core/handler/qps_consumer_flow_control_handler.go
core/handler/qps_provider_flow_control_handler.go

fix qps=0 not effective

---

core/registry/cache.go
core/registry/cache_index.go
core/registry/cache_index_test.go
core/registry/servicecenter/servicecenter.go

expose index cache

---

client/grpc/grpc.go
core/common/common.go

grpc context memory leak if don not call cancel func

---

core/registry/bootstrap.go
core/registry/heartbeat.go
pkg/runtime/runtime.go

register must register metadata

---

server/grpc/server.go

grpc protocol support provider chain

---

README.md

Signed-off-by: Wang Kirin <qilin.wang@huawei.com>

fix install instruction code and typos

---

core/registry/bootstrap.go

add missing logger param fix #452

add missing logger param

---

core/client/client_manager.go
core/client/client_manager_test.go
core/config/config.go
core/config/model/chassis.go
docs/user-guides/transport.md
examples/discovery/client/conf/chassis.yaml

support custom max idle conn

---

server/restful/context.go
server/restful/context_test.go
server/restful/form_mapping.go

add ReadQueryEntity used to read query parameters into a specified struct

add `ReadQueryEntity` used to read query parameters into a specified struct

---

core/config/archaius.go
eventlistener/event_register.go
eventlistener/lager_event_listener.go

need use this PR https://github.com/go-chassis/paas-lager/pull/18

able change lager level at runtime

---

eventlistener/lager_event_listener.go
go.mod

…pollo removed, grpc migrate to go-chassis-protocol

upgrade mod

---

server/restful/restful_server.go

Add schema generation success log.

Add schema generation success log.

---

server/restful/restful_server.go

fix:operationID is ResourceFuncName

fix:operationID is ResourceFuncName

---

core/config/schema/loader.go
core/config/schema/loader_test.go
core/lager/logrotate_test.go
core/registry/bootstrap.go
docs/getstarted/writing-rest.md
go.mod
server/restful/restful_server.go
server/restful/restful_server_test.go

fixbug:schema will not upload to service-center when first register

fixbug:schema will not upload to service-center when first register

---

chassis.go
chassis_test.go
core/server/server_manager.go
docs/user-guides/handler-chain.md

support different protocols specify different handler chains

support different protocols specify different handler chains

---

docs/user-guides.rst
docs/user-guides/java-call-go.md

add java call go doc

---

pkg/scclient/client.go
pkg/scclient/pool.go

fix #594
create a global address pool, and set address to it
then create a timer, check each address network connectivity

add sc/sd network connectivity check

---

server/restful/restful_server.go
server/restful/restfultest/restfultest.go
server/restful/restfultest/restfultest_test.go
server/restful/router.go

1. add a chain param in restfultest for unit test
2. set 2 methods in router: httpRequest2Invocation and invocation2HTTPRequest public

modify rest api test interface for unit test

---

core/registry/healthz.go

exp type is *MicroServiceInstance

fix sprintf format wrong type

---

chassis.go
core/registry/heartbeat.go

before shutting down server:
- stop heartbeat service
- unregister self instance

fix #710 - stop heartbeat service and unregistry self instances before shutting down server

---

docs/huawei/cse.md

merge auth code， client no need to import auth package

merge auth code

---

core/config/model/chassis.go
docs/user-guides/microservice.md

1. remove redundant apollo option
2. fix documentation

remove redundant apollo option

---

core/fault/fault_injection.go
core/fault/fault_injection_test.go
core/fault/fault_test.go

Fix:  服务治理错误率0% 实际触发为100%

---

pkg/loadbalancing/latency_strategy.go
pkg/loadbalancing/latency_strategy_test.go

#789 Load balance response time weight is not effective

---

README.md
core/config/lb_config.go
core/handler/handler_chain.go
core/match/match.go
core/match/match_test.go
core/provider/provider_manager.go
eventlistener/loadbalance_event_listener.go
examples/circuit/server/resource/restful_hello.go
examples/metadata/resource/restful_hello.go
scripts/travis/deadCodeChecker.sh

Fix #795 - deadcode门禁静态检查不生效
@tianxiaoliang

Fix #795 - deadcode门禁静态检查不生效

---

docs/middleware/monitoring.md
go.mod
go.sum
middleware/monitoring/handler.go
middleware/monitoring/handler_test.go
pkg/metrics/metrics.go
pkg/metrics/prometheus.go
server/restful/restfultest/restfultest.go
server/restful/restfultest/restfultest_test.go
server/restful/router.go

- unify restfultest code
- 一些通用选项不要让插件自己调archaius获取

new feature: monitoring middleware

---

chassis_init.go
examples/discovery/server/conf/chassis.yaml
examples/discovery/server/main.go
middleware/monitoring/handler.go

- 由于metrics的初始化晚于handler初始化，导致空指针
- 更改错误的延迟统计
-  修复label为空的问题

fix bug monitoring handler panic

---

go.mod
go.sum

update go-archaius version

---

server/restful/handler.go

让context在整个handler处理链之中完整的传递。#819

让context在整个handler处理链之中完整的传递。#819

---

core/config/config.go

从go-archaius获取microservice.yaml中的配置

select microservice config from archaius

---

core/config/model/chassis.go
core/config/schema/loader.go
core/config/schema/loader_test.go
core/registry/bootstrap.go
docs/user-guides/microservice.md

1、service_description增加schemas配置；2、schema模块增加自定义契约

service_description增加schemas配置

---

core/config/schema/loader.go
core/config/schema/loader_test.go
core/registry/bootstrap.go
core/registry/bootstrap_test.go

Fix: add schema order

---

go.mod
go.sum
scripts/ci/unit_test.sh

sync archaius latest version

---

core/config/config.go

go-aichaius已经支持了结构体切片的反射赋值，go-chassis把配置的任务完全依赖给配置库aichaius。

configuration reading completely depends on go-archaius

---

security/authr/authenticator.go
security/authr/authenticator_test.go
security/authr/options.go

认证与鉴权的需求非常重要，为了应对不同的交付，实现总是不同的。这就是需要在工程中进行解耦，以随时应对变换的需求
本次提交解耦认证的具体实现

feature: auth module to make auth standardized

---

security/secret/secret.go
security/secret/secret_test.go

add convenience API

---

core/handler/handler_chain.go
server/restful/router.go

fix handler chain copy
https://github.com/go-chassis/go-chassis/issues/875

fix handle chain copy

---

pkg/scclient/load_balance.go
pkg/scclient/load_balance_test.go

fix data race of the global varible i in pkg/scclient/load_balance.go

fix data race 

---

core/common/common.go
core/tls/common.go
core/tls/tls.go
docs/user-guides/tls.md

add serverName on SSLConfig #910

---

core/config/model/chassis.go
storage/options.go

add common db options struct

---

docs/user-guides/tls.md

增加 Consumer 侧 serverName 字段的解释

Add server name

---

.github/workflows/golangci-lint.yml
README.md
core/handler/loadbalance_handler.go
core/invocation/invocation.go
core/options.go
core/rest_invoker.go
server/restful/restful_server.go

- 增加注释
- 删除不需要的信息,
- 修复golangci-lint v1对githubaction出现不兼容问题导致门禁失败

add comment for invocation for better understanding

---

core/config/model/chassis.go
storage/options.go

add DB config options

---

README.md

I'd like to add two people to go chassis commiters, they both comes from huawei, which has been working on go chassis for a long time
- https://github.com/go-chassis/go-chassis/pulls?q=is%3Apr+author%3Aichiro999
- https://github.com/go-chassis/go-chassis/pulls?q=is%3Apr+author%3Ahumingcheng

add committer list

---

chassis_api.go
chassis_init.go
client/rest/rest_client.go
client/rest/restful.go
core/client/client.go
core/client/client_manager.go
core/client/transport_handler.go
core/client/transport_handler_test.go
core/handler/handler.go
core/handler/handler_chain_test.go
core/handler/loadbalance_handler.go
core/registry/cache_index.go
core/registry/servicecenter/cache.go
core/registry/struct.go
go.mod
health/healthz.go
health/healthz_test.go
pkg/util/httputil/httputil.go

原则：
- **handler实现紧跟他所包装的功能模块**，因此将transport handler挪到了client pkg里
- **transport handler只负责编排client接口，不该理解具体的协议实现**，因此，将status的设置过程抽象为需要实现的interface
逐步将net/http解耦将第二个原则贯彻到底

逐步解耦传输层对具体协议实现的依赖

---

README.md
README_cn.md

chore: add ieg log

---

storage/options.go

Set to the path of the file that contains the TLS/SSL certificate.

Add certfile field in options

---

.github/workflows/golangci-lint.yml
core/config/schema/loader.go

https://github.com/go-chassis/go-chassis/issues/957

schema目录扫描失败跳过即可，打印warn日志，不return error

---

.readthedocs.yaml
docs/conf.py
docs/requirements.txt

fix doc build failed

---

core/config/sd_config.go
core/registry/bootstrap.go
docs/user-guides/registry.md

【issue】: #999
【特性/模块名称】：bug修复
【修改内容】：
1.注册实例时候默认不注册schema
2.修改注册完之后跟新properties条件判断，之前漏判断导致每次都会去调用跟新properties接口
【自测情况】：
测试通过

注册实例时候默认不注册schema到service-center #999

---

docs/middleware/access-log.md
docs/middleware/monitoring.md
docs/user-guides/metrics.md
middleware/monitoring/handler.go

have an unified prefix to distinguish from other system metrics

rename metrics name

---

core/tls/common.go
core/tls/tls.go
core/tls/tls_test.go

support tls 1.3

---

core/config/model/chassis.go
core/config/model/cors.go
docs/user-guides/protocols.md
pkg/goplugin/plugin_disable.go
pkg/goplugin/plugin_enable.go
server/restful/restful_server.go

add cors support

---

control/servicecomb/transfer.go
control/servicecomb/transfer_test.go

serverListFilters configuration does not take effect

serverListFilters configuration does not take effect

---

examples/schemas/restful_hello.go
examples/schemas/restful_router_V1.go
examples/schemas/restful_router_V2.go

I'm new to goLang.
Found spell error "reslut" when try rest example in Get Started doc.

fix spell error:reslut

---

client/rest/rest_client_test.go

add assertion to make sure http reponse can return back

---

core/server/options.go

https://github.com/gofiber/fiber
a route programing model like below
if I want to make fiber as plugin, I need more options to register a route

to support more rest framework

---

go.mod
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/prometheus.go

add GaugeValue and CounterValue interfaces

---

core/lager/lager.go

[feat] the size of log support 500M

[feat] the size of log support 500M
