go-chassis/go-chassis

config-center/config_center.go
core/util/string/string.go

When I use `go vet $(go list ./...| grep -v /vendor/| grep -v /third_party/)` scan our project ,it comes out  following warnings 
```bash
config-center/config_center.go:42: missing argument for Errorf("%s"): format reads arg 3, have only 2 args
config-center/config_center.go:131: no formatting directive in Errorf call
config-center/config_center.go:144: no formatting directive in Errorf call
exit status 1
core/util/string/string.go:79: possible misuse of unsafe.Pointer
exit status 1
```
This PR fix that 
Signed-off-by: WangQilin <qilin.wang@huawei.com>

fix go vet warning

---

core/fault/fault.go
core/handler/fault_inject_handler.go
core/handler/fault_inject_handler_test.go

added error struct for fault injection to be used in mesher reverse proxy

added error struct for fault injection

---

eventlistener/event_register.go
eventlistener/loadbalance_event_listener.go

Update of loadbalance successiveFailedTimes configuration can be missed if it is not watched.

Add event key successiveFailedTimes to watched keys

---

core/handler/tracing_handler.go
core/invocation/invocation.go
core/invocation/invocation_test.go
core/options.go
core/rest_invoker.go
core/rpc_invoker.go
server/restful/context.go
server/restful/restful_server.go

add api for header, metadata in invocation 
unify headers to ctx
don not allocate mem for matadata or ctx map if user never use it, that is to improve perf
set inv ctx to restful handler

set inv ctx to restful handler 

---

client/highway/highway_base_client.go

问题：Wait管道处理有问题，违反管道处理原则（发送方关闭管道），当吞吐量达到5000以上时，有可能报以下错误
panic: send on closed channel
goroutine 144 [running]:
github.com/go-chassis/go-chassis/client/highway.(*InvocationContext).Done(...)
/Users/heavyrainlee/go/src/github.com/go-chassis/go-chassis/client/highway/highway_base_client.go:47
github.com/go-chassis/go-chassis/client/highway.(*ClientConnection).processMsg(0xc420350140, 0xc42cb63860)
/Users/heavyrainlee/go/src/github.com/go-chassis/go-chassis/client/highway/client_conn.go:100 +0x8c
github.com/go-chassis/go-chassis/client/highway.(*ClientConnection).msgRecvLoop(0xc420350140)
/Users/heavyrainlee/go/src/github.com/go-chassis/go-chassis/client/highway/client_conn.go:91 +0xd3
created by github.com/go-chassis/go-chassis/client/highway.(*ClientConnection).Open …

bug fix: panic if call Done for multiple times,  if there is err clear the ctx

---

core/loadbalancer/latency_strategy.go
core/loadbalancer/struct.go

ReceiveData function use Separator of ":"   split  serviceKey，But the incoming parameter serviceKey is spliced using "|" ，The will one more “|” character after serviceName ， so  alter Separator  of “|” in ReceiveData function to split  serviceKey。 SaveLatency save latest 10 record,but save latest 11

alter ReceiveData function

---

core/registry/util.go
core/registry/util2_test.go
go.mod
pkg/util/iputil/ip.go
pkg/util/iputil/ip_test.go

When provider listening on *all IP*, go-chassis will register `0.0.0.0` to service center, but consumer should know the specified IP address instead `0.0.0.0`, otherwise the consumer calls will go failure.
This PR fixes the logic when provider config `0.0.0.0` as the `listenAddress` or `advertiseAddress` in `chassis.yaml`, one of local NIC's IP address will be used when registering to service center.
For `iputil.GetLocalIP()`, use `IsGlobalUnicast()` to filter local loopback / local unicast or unspecified addresses out.

Bugfix: fix provider's endpoint registered to service center

---

core/registry/bootstrap.go
core/server/server_test.go
pkg/util/iputil/ip.go
server/grpc/server.go
server/highway/highway_server.go
server/restful/restful_server.go

For Issue #524
Ability to use random port to start server, just using :0 as port, example:
`listenAddress: 0.0.0.0:0`
允许使用随机端口监听服务，该修改已可以满足当前使用，未大幅度更改当前启动机制，请检视代码以确认代码更改合理性

Using random port to start server

---

core/registry/bootstrap.go
core/registry/heartbeat.go
core/server/options.go
core/server/server_manager.go
server/restful/restful_server.go

if i register 
rest:
listenAddress: 127.0.0.1:30101
rest-admin:
listenAddress: 127.0.0.1:30102
will only rest://127.0.0.1:30102 on sc.
if find it on mesher.
if i register by mesher
rest:
listenAddress: 127.0.0.1:30101
rest-admin:
listenAddress: *.*.*.*:30102
on sc.
rest://127.0.0.1:30102
rest-admin://*.*.*.*:30102
rest protocol port will change

bug fix: can not register the same prefix protocol

---

server/restful/restful_server.go
server/restful/restful_server_test.go

Bugfix: go-chassis will return 406 if `Produces` not been defined but `Accept` exist in request headers

---

go.mod

The default `go.mod` introduces a couple of `atomic` go modules with different paths, see:
The root cause is `ratelimit` uses incorrect `atomic` module path in its test files, an issue was raised and solved recently, find it here: https://github.com/uber-go/ratelimit/issues/18
This PR it going to fix duplicate atomic requirement packages path issue. 
FYI: the differences between the old and new imported version of `ratelimit`:
https://github.com/uber-go/ratelimit/compare/c15da02342779cb6dc027fc95ee2277787698f36...cd1f0abeddc3fe992a7be8d533332897936efbc0

Bugfix: Update go.mod to fix duplicate atomic requirement packages path issue

---

docs/README.md
docs/dev-guides.rst
docs/dev-guides/restful.md
server/restful/restful_server.go
server/restful/restfultest/restfultest.go
server/restful/restfultest/restfultest_test.go
server/restful/router.go
server/restful/router_test.go

feat:
- group route: now we can emit repeatable pre-path by implement GroupPath();
```
func (r *DummyResource) GroupPath() string{
return "/demo"
}
```
- direct register hanler function;
```
func (r *DummyResource) URLPatterns() []restful.Route {
return []restful.Route{
{Method: http.MethodGet, Path: "/sayhello/{userid}", ResourceFuncName: "Sayhello",
Returns: []*restful.Returns{{Code: 200}}},
// we can register handler function to optimize performance
{Method: http.MethodGet, Path: "/sayhello2/{userid}", ResourceFunc:r.Sayhello,
Returns: []*restful.Returns{{Code: 200}}},
}
}
```
- add panic recover to restful handler
```
defer func() {
if r := recover(); r != nil {
openlogging.Error(fmt.Sprintf("handle request panic. path:%s, panic:%s", route.Path, r))
if err := …
```

some feats as description

---

core/fault/fault_injection.go

fault-injector bug #767
修复下面问题:
1. 之前代码有多协程安全问题;
2. 之前代码，不能同时支持abort 和 delay
3. 之前的对于每个请求，不能按照percentage等概率触发； 我的理解是每次请求时独立的，应该每次等概率发生
4. 整数和浮点数比较，不安全 0 和 0.0， 100和100.0

fault-injector fix #767

---

core/registry/bootstrap.go

修改原因：在正常先chassis.Init()再chassis.Run()的情况下，会依次执行RegisterService()->CreateLocalSchema()->RegisterServiceInstances()。当前AddSchemas()在RegisterService()函数中，执行到此处时还没有自动生成schema文件（schema文件在CreateLocalSchema()函数中生成），因此首次启动时不会成功注册schema。
修改内容：将AddSchemas()动作移到RegisterServiceInstances()中执行。

#782 Move add schemas action to the RegisterServiceInstances method

---

go.mod
go.sum
server/restful/restful_server.go
server/restful/router.go

当前不支持用代码定义swagger中的response headers，目前依赖的go-restful库和go-restful-swagger20库已更新，go-chassis相应做修改以支持定义response headers
相关PR：
https://github.com/emicklei/go-restful/pull/426
https://github.com/go-chassis/go-restful-swagger20/pull/5
Fixes #805

support describing response headers

---

core/config/struct.go
core/registry/endpoint_struct.go
core/registry/healthz.go
core/registry/servicecenter/cache.go
core/registry/struct.go
core/router/router.go
core/router/servicecomb/route_rule_listener.go
core/router/servicecomb/router.go
docs/intro/features.rst
docs/user-guides.rst
docs/user-guides/profile.md
pkg/profile/profile.go
pkg/profile/profile_test.go
server/restful/restful_server.go

新增profile接口，用于查询程序当前缓存中的路由规则和已经发现的微服务实例信息。可以方便定位路由和注册发现相关的问题

add profile interface

---

middleware/monitoring/handler.go

为了实现go chassis轻量化，引导开发者按需引用中间件

light weight: decouple rate limiter to middleware

---

docs/middleware/jwt.md
examples/jwt/main.go
go.sum
middleware/jwt/api.go
middleware/jwt/handler.go

jwt.Use这个API应当在任意位置可以调用，但是老的实现导致调这个api，handler才会被安装到框架，这样就严重影响了代码执行顺序的自由性

jwt middleware should install in init() function

---

configserver/config_server.go
core/config/model/chassis.go
core/core_test.go
core/governance/process.go
core/handler/invocation_mark_handler.go
core/handler/router_handler.go
core/marker/marker.go
core/marker/marker_test.go
core/marker/operator.go
core/marker/operator_test.go
core/registry/util.go
core/router/router.go
core/router/router_test.go
docs/user-guides/router.md
pkg/util/iputil/ip.go
pkg/util/iputil/ip_test.go

路由策略管理变得更加强大：
- 可以引用match策略定义，只需要通过名字即可引用复杂的模板定义
- source template功能被移除，被上述能力替代
模板的匹配能力可以参考 #754 
需要在handler chain中配置“marker”用来进行流量标记
其他变动：
删除依赖定义的能力，没有实际业务场景

router management can refer to match policy

---

docs/user-guides/marker.md
middleware/monitoring/handler.go
middleware/monitoring/handler_test.go

监控中间件没有对业务结果进行返回，导致http response错误

bug fix: monitoring should call original call back func

---

middleware/jwt/handler.go
middleware/jwt/handler_test.go

jwt一般会配置在handler chain中，但是业务服务可能会有启用或未启用认证的场景，未启用场景下，不该进行jwt认证

if jwt is not init, skip auth

---

core/config/struct.go
core/governance/governance_test.go
core/governance/process.go
core/handler/invocation_mark_handler_test.go
core/marker/marker.go
core/marker/marker_test.go
core/router/router_test.go
docs/user-guides/marker.md
docs/user-guides/router.md
examples/marker/conf/chassis.yaml
middleware/ratelimiter/handler.go
middleware/ratelimiter/handler_test.go
resilience/rate/limiter.go

增强了流量标记的规则能力，提供了更强的"或"语义，允许定义多个matches规则
```yaml
servicecomb:
match:
accessAdminAPI: |
matches:
- apiPath:
exact: "/role"
- apiPath:
exact: "/account"
```

enhance marker match policy

---

core/router/router.go
core/router/router_config.go
core/router/router_config_test.go
core/router/router_test.go
core/router/servicecomb/route_rule_listener.go

#930
1.修复当一个服务配置了多个优先级的分发策略情况下，第一个匹配的优先级下的分发策略就会被当做这个服务其他优先级的分发策略，这样当满足其他优先级的请求就会导致该优先级下的分发策略失效。
2.修复当一个优先配置了权重为0的tag，则第一个满足这个优先级的第一个请求就会返回权重为0的tag
3.增加单元测试

修复router中发现的bug

---

core/core_test.go
core/handler/loadbalance_handler.go
core/options.go
core/rest_invoker.go
core/rpc_invoker.go
examples/simple/README.md
examples/simple/client/conf/chassis.yaml
examples/simple/client/conf/microservice.yaml
examples/simple/client/main.go
examples/simple/server/conf/chassis.yaml
examples/simple/server/conf/microservice.yaml
examples/simple/server/main.go

微服务架构模式只是go chassis的核心功能之一，所以做了一个设计保证和微服务架构模式解耦。但是体验并不好
过去的设计要通过WithEndpoint(endpoint)接口手工指定微服务入口，强制决定服务地址来绕过客户端负载均衡（包含服务发现）。但其实这个方法的参数是个冗余信息，还可以填写的完全不一致，导致用户困惑
比如重复信息
```go
invoker:= core.NewRestInvoker()
req, _ := rest.NewRequest("GET", "http://127.0.0.1/hello", nil)
invoker.ContextDo(context.TODO(), req, core.WithEndpoint("127.0.0.1"))
```
比如导致困惑
```go
req, _ := rest.NewRequest("GET", "http://orderService/hello", nil)
invoker.ContextDo(context.TODO(), req, core.WithEndpoint("127.0.0.1"))
```
**新的API设计不再需要传参，而是复用request内的host信息，方便许多**
比如利用kubernetes的原生容器网络，或者结合任意服务网格
```go
req, _ := rest.NewRequest("GET", "http://orderService:8080/hello", nil)
invoker.ContextDo(context.TODO(), req, core.WithoutSD())
```
比如直接使用网络地址
```go
req, _ := rest.NewRequest("GET", "http://127.0.0.1:8080/hello", …
```

more friendly for user who don't want to use service discovery

---

client/rest/rest_client.go
client/rest/rest_client_test.go

1.为Client增加关闭空闲连接，可以及时回收资源；
2.删除多余代码

为Client增加关闭空闲连接，可以及时回收资源；删除多余代码

---

storage/options.go

Set to the path of the file that contains the TLS/SSL certificate and key.

Add keyfile field in options

---

control/servicecomb/qps_event_listener.go
control/servicecomb/qps_event_listener_test.go

限流配置下发有可能int被当做string处理
而老的实现没有在出现问题后返回，所以导致限流一直为0，服务服务访问，修复方式：支持string格式的变量，无法转为int立刻返回

bugfix: able to handler string value

---

core/server/options.go
core/server/server_manager.go
go.mod
go.sum
server/restful/restful_server.go

https://github.com/go-chassis/go-chassis-extension/tree/master/protocol/gin4r 
gin作为插件不该有archaius的学习成本，应该保证archaius不被协议插件的开发者感知，降低门槛

decouple archaius from protocol plugin impl

---

core/tls/tls.go
docs/user-guides/tls.md

Common certificate in ugly scene ，Consumer TLS configuration supports through compensation；
such as rest.consumer.verifyPeer： xxxxx
https://github.com/go-chassis/go-chassis/issues/979

feature: Consumer TLS config supports through compensation

---

middleware/accesslog/access_log.go

LogRotateCompress和LogRotateDisable不能传递到seclog
LogRotateCompress为是否开启压缩的参数，默认值为false，不开启
LogRotateDisable为是否开启绕接的参数，默认是开启

access log 不能进行绕接

---

core/lager/lager.go
core/registry/heartbeat.go
core/registry/mock/mock.go
core/registry/registrator.go
core/registry/servicecenter/servicecenter.go
core/registry/servicecenter/servicecenter_test.go
docs/user-guides/log.md
go.mod
go.sum

- 若用户将打印到标准输出的日志重定向到文件，则日志中将带有颜色控制字符。为适配这种使用场景，添加颜色控制选项，允许强制开启、关闭，或自动控制。
- endpoint健康检查是解决“部分endpoint不可用导致调用失败”问题，该问题在普通的调用中就要解决，而非只在endpoint同步时才要解决，因此默认开启。

添加LogColorMode选项；默认打开client endpoint health check

---

control/panel_test.go
control/servicecomb/panel_test.go
core/client/client_manager.go
core/client/client_manager_test.go
core/config/cb_config.go
core/config/config.go
core/config/model/circuit_breaker.go

What type of PR is this?
/bugfix
What this PR does / why we need it:
**error**：
`
{"level":"INFO","timestamp":"2021-11-11 11:37:58.989 +08:00","file":"servicecomb/transfer.go:118","msg":"save circuit breaker config [hystrix.CommandConfig{MaxConcurrentRequests:100, RequestVolumeThreshold:20, SleepWindow:10000, ErrorPercentThreshold:10, ForceFallback:false, CircuitBreakerEnabled:false, ForceOpen:false, ForceClose:false, MetricsConsumerNum:0}] for [] "}
{"level":"INFO","timestamp":"2021-11-11 11:37:58.990 +08:00","file":"servicecomb/transfer.go:118","msg":"save circuit breaker config [hystrix.CommandConfig{MaxConcurrentRequests:1000, RequestVolumeThreshold:20, SleepWindow:15000, ErrorPercentThreshold:50, ForceFallback:false, CircuitBreakerEnabled:false, ForceOpen:false, ForceClose:false, …

bugfix: Parse services from config failed: input must be an ptr

---

pkg/backends/quota/manage_test.go
pkg/backends/quota/manager.go
pkg/backends/quota/options.go

- 增加覆盖配额的方法，方便业务使用
- service的设计考虑不全面，实际上大部分的场景下service并发必选项，重命名为namespace，并放到option中，有需要的业务可以考虑集成
- 统一resource的命名为resourceType

refactor quota management

---

core/lager/lager_test.go

Found core/lager/lager_test.go does not clean up log dir after test complete.
Check if function t.Cleanup(added in go1.14) is allowed to use before merge.
ref: [t.Cleanup](https://pkg.go.dev/testing#T.Cleanup)
Thx!

fix test: clean up log dir after test complete

---

bootstrap/bootstrap_test.go
chassis_api_test.go
control/servicecomb/panel_test.go
core/config/cb_config_test.go
core/config/cd_config_test.go
core/config/config_test.go
core/config/schema/loader_test.go
core/handler/handler_chain_test.go
core/handler/handler_test.go
core/handler/loadbalance_handler_test.go
core/invocation/invocation_test.go
core/lager/lager_test.go
core/loadbalancer/loadbalancer_test.go
core/registry/servicecenter/cache_test.go
core/registry/servicecenter/client_test.go
core/registry/servicecenter/servicecenter_test.go
core/router/router_test.go
core/tls/tls_test.go
middleware/circuit/bizkeeper_handler_test.go
middleware/ratelimiter/qps_consumer_flow_control_handler_test.go
pkg/util/fileutil/fileutil_test.go
security/cipher/plugins/aes/aes.go

To avoid one test influence another with Setenv, suggest to add defer to cleanup env  var setting in test.
Before go1.17:
``` golang
os.Setenv("CHASSIS_HOME", "test")
defer os.Unsetenv("CHASSIS_HOME")
```
go1.17 and later:
```golang
func (t *T) Setenv(key, value string)
````
https://pkg.go.dev/testing#T.Setenv
https://cs.opensource.google/go/go/+/go1.18:src/testing/testing.go;l=1280

fix test: exec Unsetenv after test complete

---

core/lager/lager.go

此次变更将提供设置日志文件不老化的选项，也即LogRotateAge=0
以前情况：不设置老化天数LogRotateAge或者设置LogRotateAge=0，系统将默认设置LogRotateAge=1，也即老化天数默认为1天

allow logRotateAge option to be set to 0

---

core/common/common.go
core/invocation/invocation.go
middleware/monitoring/handler.go
server/restful/restful_server.go

monitoring middleware 不再只能监控http 请求，而是以invocation作为唯一标准模型，实现了真正的协议实现和框架实现无关

new feature: able to observe API pattern and method name
